##probamos la api
GET http://localhost:3000/api/prod/
###cargamos un registro de producto
POST http://localhost:3000/api/prod
Content-Type: application/json

{
    "nombre":"coca cola",
    "descripcion":"coca cola persona  ",
    "categoria":"Refrescos",
    "precio":"2.50",
    "cantidad":"50",
    "imagen":"/home/henrry/Imágenes/refrescos/coca_cola_190ml.webp"
}   