### para consultar usuarios
GET http://localhost:3000/api/users
### para consultar usuarios por id
GET http://localhost:3000/api/users/1
### para crear un usuario
POST http://localhost:3000/api/users/
Content-Type: application/json

{
    "nombres": "Luis ",
    "apellidos": "Gomez Soliz",
    "ci": 3493824,
    "correo": "luis.gomez@example.com",
    "telefono": "54345622",
    "contra": "mycontraseña"
}